# Numpy exercise

In [2]:
import numpy as np

### 1. 0이 10개 포함된 벡터

In [3]:
ex_one = np.zeros(10)
print(f'shape: {ex_one.shape}')
print(f'ex_one = {ex_one}')

shape: (10,)
ex_one = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2. 1~9 까지 벡터

In [4]:
ex_two = np.arange(1,10)
print(f'shape: {ex_two.shape}')
print(f'ex_two = {ex_two}')

shape: (9,)
ex_two = [1 2 3 4 5 6 7 8 9]


### 3. 0~9까지 벡터 생성 후 거꾸로 뒤집기

In [5]:
ex_three = np.arange(10)
ex_three = ex_three[::-1]
print(f'shape: {ex_three.shape}')
print(f'ex_three = {ex_three}')

shape: (10,)
ex_three = [9 8 7 6 5 4 3 2 1 0]


### 4. 리스트에서 3x3 행렬 생성

$$
\begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8
\end{bmatrix}
$$

In [6]:
ex_four = np.arange(9).reshape(3, 3)
print(f'shape: {ex_four.shape}')
print(f'ex_four = \n{ex_four}')

shape: (3, 3)
ex_four = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. 항등행렬 (Identity matrix)

$$
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In [7]:
ex_five = np.eye(3)
print(f'shape: {ex_five.shape}')
print(f'ex_five = \n{ex_five}')

shape: (3, 3)
ex_five = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 6. 3x3 행렬의 성분을 난수로 채우기

$$
\begin{bmatrix}
0.42 & 0.72 & 0.00\\
0.3 & 0.15 & 0.09\\
0.19 & 0.35 & 0.4
\end{bmatrix}
$$

In [8]:
np.random.seed(1)
ex_six = np.random.random((3, 3))
ex_six = ex_six.round(2)
print(f'shape: {ex_six.shape}')
print(f'ex_six = \n{ex_six}')

shape: (3, 3)
ex_six = 
[[0.42 0.72 0.  ]
 [0.3  0.15 0.09]
 [0.19 0.35 0.4 ]]


### 7. 행렬의 성분이 모두 1인 3x3 행렬

$$
\begin{bmatrix}
1 & 1 & 1\\
1 & 1 & 1\\
1 & 1 & 1
\end{bmatrix}
$$

In [9]:
ex_seven = np.ones((3, 3))
print(f'shape: {ex_seven.shape}')
print(f'ex_seven = \n{ex_seven}')

shape: (3, 3)
ex_seven = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 8. 행렬의 연산 - 전치행렬

$$
\begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8
\end{bmatrix}^\mathsf{T}
=
\begin{bmatrix}
0 & 3 & 6\\
1 & 4 & 7\\
2 & 5 & 8
\end{bmatrix}
$$

In [10]:
ex_eight = np.transpose(ex_four)
print(f'shape: {ex_eight.shape}')
print(f'before transpose:\n{ex_four}')
print(f'after transpose:\n{ex_eight}')

shape: (3, 3)
before transpose:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
after transpose:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


### 9. 행렬의 연산 - 행렬 곱셈 (Matrix Multiplication)

$$
\begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8
\end{bmatrix}
\times
\begin{bmatrix}
0 & 3 & 6\\
1 & 4 & 7\\
2 & 5 & 8
\end{bmatrix}
=
\begin{bmatrix}
5 & 14 & 23\\
14 & 50 & 86\\
23 & 86 & 149
\end{bmatrix}
$$

In [11]:
ex_nine = ex_four.dot(ex_eight)
print(f'A = \n{ex_four}')
print(f'B = \n{ex_eight}')
print(f'AxB = \n{ex_nine}')

A = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B = 
[[0 3 6]
 [1 4 7]
 [2 5 8]]
AxB = 
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


### 10. 인덱싱

In [12]:
print(f'ex_nine: \n{ex_nine}\n')
print(f'a_11 = {ex_nine[0, 0]}')  # 1행 1열 원소
print(f'a_21 = {ex_nine[1, 0]}')  # 2행 1열 원소
print(f'a_13 = {ex_nine[0, 2]}')  # 1행 3열 원소

ex_nine: 
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]

a_11 = 5
a_21 = 14
a_13 = 23


### 11. 행렬 슬라이싱

In [13]:
print(f'ex_nine: \n{ex_nine}')
print('ex_nine[0:2, 0:2] \n', ex_nine[0:2, 0:2])
print('ex_nine[1:3, 0:3] \n', ex_nine[1:3, 0:3])
print('ex_nine[1:3, :] \n', ex_nine[1:3, :])
print('ex_nine[:, :] \n', ex_nine[:, :])
print('ex_nine[:2, 1:] \n', ex_nine[:2, 1:])
print('ex_nine[:2, 0] \n', ex_nine[:2, 0])

ex_nine: 
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
ex_nine[0:2, 0:2] 
 [[ 5 14]
 [14 50]]
ex_nine[1:3, 0:3] 
 [[ 14  50  86]
 [ 23  86 149]]
ex_nine[1:3, :] 
 [[ 14  50  86]
 [ 23  86 149]]
ex_nine[:, :] 
 [[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
ex_nine[:2, 1:] 
 [[14 23]
 [50 86]]
ex_nine[:2, 0] 
 [ 5 14]


### 12. 행렬을 벡터로 변환 (Vectorization)

$$
A=
\begin{bmatrix}
0.42 & 0.72 & 0.00\\
0.3 & 0.15 & 0.09\\
0.19 & 0.35 & 0.4
\end{bmatrix}
\longrightarrow
vec(A)=
\begin{bmatrix}
0.42 & 0.72 & 0.00 & 0.3 & 0.15 & 0.09 &0.19 & 0.35 & 0.4
\end{bmatrix}
$$

In [14]:
print(f'ex_six = \n{ex_six}')
ex_twelve = ex_six.flatten()
print(f'vec(ex_six) = {ex_twelve}')

ex_six = 
[[0.42 0.72 0.  ]
 [0.3  0.15 0.09]
 [0.19 0.35 0.4 ]]
vec(ex_six) = [0.42 0.72 0.   0.3  0.15 0.09 0.19 0.35 0.4 ]


### 13. 정렬

In [16]:
print(f'ex_twelve = {ex_twelve}')
print('오름차순 정렬:')
ex_thirteen_asc = np.sort(ex_twelve)
print(f'ex_thirteen_asc = {ex_thirteen_asc}')
print('내림차순 정렬:')
ex_thirteen_desc = np.sort(ex_twelve)[::-1]
print(f'ex_thirteen_desc = {ex_thirteen_desc}')

ex_twelve = [0.42 0.72 0.   0.3  0.15 0.09 0.19 0.35 0.4 ]
오름차순 정렬:
ex_thirteen_asc = [0.   0.09 0.15 0.19 0.3  0.35 0.4  0.42 0.72]
내림차순 정렬:
ex_thirteen_desc = [0.72 0.42 0.4  0.35 0.3  0.19 0.15 0.09 0.  ]
